### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by lemunozm** [frewsxcv/rust-dark-light#1]
Hi! are there any ideas for Linux support?

**Comment by frewsxcv** [comment]
I don't have a Linux machine so I won't be able to help much, but I'd accept a PR if someone opened one. What is the story for dark mode on Linux? I assume it depends which desktop environment you use

**Comment by lemunozm** [comment]
Yeah, it depends of the desktop environment. For example for gnome (one of most used), I think it could be reached using gsettings (gtk-rs crate).

**Comment by edfloreshz** [comment]
I can help, I already implemented code for KDE Plasma.

**Comment by Seirdy** [comment]
The cross-platform way to do this on Freedesktop-complaint platforms will be through the `color-scheme` key of [xdg-desktop-portal's `org.freedesktop.appearance` interface](https://flatpak.github.io/xdg-desktop-portal/portal-docs.html). This will be implemented in GNOME 42 and will probably be implemented across Flatpak with time; libadwaita apps should already support it if available. As this is a Freedesktop standard, I imagine that KDE will follow this path too.

If you want to test this out and have `xdg-desktop-portal-gnome` and/or `xdg-desktop-portal-gtk` installed, you should be able to test it out if you install the [color-scheme simulator](https://gitlab.gnome.org/exalm/color-scheme-simulator), a portal that provides a shim interface.

**Comment by Seirdy** [comment]
Turns out that KDE already merged support into `xdg-desktop-portal-kde` two weeks ago; see [MR 52](https://invent.kde.org/plasma/xdg-desktop-portal-kde/-/merge_requests/52).

So using this interface should grant across the GNOME and KDE desktop portals. By extension, many Flatpak apps will also be supported.

**Comment by frewsxcv** [comment]
https://github.com/frewsxcv/rust-dark-light/pull/4
