### ISSUE TITLE
Does not build on macos with target x86_64-pc-windows-gnu

### ISSUE THREAD

**Issue by Piping** [frewsxcv/rust-dark-light#18]
Hi,

The current setup is to build this crate on macos with cross compiling target to x86_64-pc-windows-gnu.

The build process error out on 
```
error: native frameworks are only available on macOS targets
```

Is it possible for this to be fixed?

The steps to reproduce:
```
rustup target add x86_64-pc-windows-gnu
cargo build --release --target x86_64-pc-windows-gnu
```

Thanks!

**Comment by Be-ing** [comment]
Was this fixed by #19?

**Comment by Piping** [comment]
@Be-ing Yes, the #19 fixe the cross compiling issue.

**Comment by Be-ing** [comment]
Thanks for confirming.
