### ISSUE TITLE
Does not detect mode change

### ISSUE THREAD

**Issue by kek** [frewsxcv/rust-dark-light#29]
@edfloreshz writes in https://github.com/frewsxcv/rust-dark-light/issues/3#issuecomment-1013984546, "I'm calling dark-light::detect on a loop and invoking the callback function when the theme changes." which indicates to me that it should at least under some circumstances be possible to call the `detect` function several times during the lifetime of a program and get the current setting. However this does not seem to be the case for me since it only reports what the setting was when the program was started.

Attaching a kind of test case:

```rust
fn main() {
    println!("Darklight mode: {:?}", dark_light::detect());
    println!("Change your mode and press enter");
    let mut input = String::new();
    std::io::stdin().read_line(&mut input).unwrap();
    println!("Darklight mode: {:?}", dark_light::detect());
}
```

Output:

```
Lightness mode: Light
Change your mode and press enter

Lightness mode: Light
```

Tested on Macos 13.3.1.

**Comment by AregevDev** [comment]
Bump. It works as intended on Windows 11.
Will test on my KDE machine later.

**Comment by edfloreshz** [comment]
@kek Unfortunately I'm unable to test this on macOS, I don't own a Mac. Perhaps someone else could help us replicate this issue?

**Comment by kek** [comment]
Would a screen recording help? Also, it might be useful for me to check if this is still an issue.

**Comment by edfloreshz** [comment]
Sure, you can add it to the issue description.

**Comment by fenhl** [comment]
I can reproduce this issue on macOS 14.2.1.

**Comment by jacksongoode** [comment]
Hmm, is this planning on being fixed?

**Comment by rickykresslein** [comment]
I can reproduce this issue on 14.6.1.

**Comment by casperstorm** [comment]
Same for macOS 14.3.1.
