### ISSUE TITLE
Release v1.2.0 to include notifications

### ISSUE THREAD

**Issue by edfloreshz** [frewsxcv/rust-dark-light#38]
We should probably close #34 before making a new release.

**Comment by jacksongoode** [comment]
I would say notifications are a major feature.

**Comment by edfloreshz** [comment]
Yup! Definitely

**Comment by rickykresslein** [comment]
A new release with all of the recent improvements would be great.

**Comment by 4e554c4c** [comment]
Since #46 is merged this is ready, right?

**Comment by edfloreshz** [comment]
Closing this in favor of #51
